[SERVICE]
    Flush        1
    Log_Level    info
    Daemon       off

[INPUT]
    Name         tail
    Path         /var/log/kaizendesk/*.log
    Tag          kaizendesk.api
    Refresh_Interval 2
    Mem_Buf_Limit 10MB
    Skip_Long_Lines On

[OUTPUT]
    Name         opensearch
    Match        kaizendesk.api
    Host         opensearch
    Port         9200
    Index        kaizendesk-logs
    Logstash_Format On
    Suppress_Type_Name On
    Retry_Limit  False

[FILTER]
    Name      lua
    Match     kaizendesk.api
    script    /fluent-bit/etc/scripts/truncate_log.lua
    call      truncate
