// data.js — KaizenDesk seed data
window.KD_DATA = (function () {
  const products = [
    { id: "uts", name: "Üretim Takip Sistemi & Sunucu", issues: ["SQL Senkronizasyon Hatası", "Sunucu Veri Yazma Gecikmesi", "MES Arayüz Donması", "Diğer"] },
    { id: "kanban", name: "e-Kanban ve Otonom Lojistik", issues: ["AGV Rota / Bağlantı Kaybı", "Dijital Kanban Kartı Okuma Hatası", "Wi-Fi Sinyal Zayıflığı", "Diğer"] },
    { id: "qc", name: "Dijital Kalite Kontrol", issues: ["Akıllı Tork Tabancası Bağlantı Sorunu", "Sensör İletişim Hatası", "Kalite Veritabanı Erişim Sorunu", "Diğer"] },
    { id: "net", name: "Endüstriyel Ağ ve Saha Bağlantısı", issues: ["Access Point Donanım Arızası", "El Terminali IP Çakışması", "Port Aktivasyon Talebi", "Diğer"] },
    { id: "other", name: "Diğer", issues: ["Diğer"] },
  ];

  const agents = [
    { id: "u1", name: "Mert Aydın",     initials: "MA", team: "Ağ & Saha" },
    { id: "u2", name: "Selin Korkmaz",  initials: "SK", team: "Üretim Takip" },
    { id: "u3", name: "Burak Yılmaz",   initials: "BY", team: "Kalite Kontrol" },
    { id: "u4", name: "Deniz Aksoy",    initials: "DA", team: "e-Kanban" },
    { id: "u5", name: "Hülya Tuna",     initials: "HT", team: "Üretim Takip" },
  ];
  const customers = [
    { id: "c1", name: "Ahmet Çelik",   initials: "AÇ", dept: "Montaj Hattı 3" },
    { id: "c2", name: "Esra Demir",    initials: "ED", dept: "Boyahane" },
    { id: "c3", name: "Kerem Şahin",   initials: "KŞ", dept: "Lojistik" },
    { id: "c4", name: "Pınar Aslan",   initials: "PA", dept: "Kalite Güvence" },
  ];
  const manager = { id: "m1", name: "Cem Toprak", initials: "CT", role: "Yönetici" };

  // Status workflow: New → In Progress → Waiting for Customer → Resolved → Closed
  const tickets = [
    {
      id: "TK-2841", title: "MES arayüzü ekran 4'te 30sn aralıklarla donuyor",
      productId: "uts", issue: "MES Arayüz Donması",
      priority: "high", status: "in_progress",
      reporter: "c1", assignee: "u2",
      createdAt: "2026-04-30T08:14:00",
      updatedAt: "2026-05-02T09:21:00",
      slaDeadline: "2026-05-02T16:14:00",
      slaTarget: 8 * 60,
      tags: ["#mes", "#hat-3"],
      worklog: [{ user: "u2", min: 45, when: "2026-05-01T14:30", note: "Log toplama, replication kontrolü" }],
      attachments: [{ name: "mes-error.log", size: "248 KB", kind: "log" }, { name: "ekran-1.png", size: "412 KB", kind: "img" }],
    },
    {
      id: "TK-2840", title: "AGV-07 koridor B5'te bağlantı kaybediyor",
      productId: "kanban", issue: "AGV Rota / Bağlantı Kaybı",
      priority: "critical", status: "in_progress",
      reporter: "c3", assignee: "u4",
      createdAt: "2026-05-02T06:02:00",
      updatedAt: "2026-05-02T10:12:00",
      slaDeadline: "2026-05-02T10:02:00",
      slaTarget: 4 * 60,
      tags: ["#agv", "#sla-risk"],
      breached: true,
      worklog: [],
      attachments: [],
    },
    {
      id: "TK-2839", title: "Akıllı tork tabancası kalibrasyon verilerini iletmiyor",
      productId: "qc", issue: "Akıllı Tork Tabancası Bağlantı Sorunu",
      priority: "high", status: "waiting_customer",
      reporter: "c4", assignee: "u3",
      createdAt: "2026-05-01T11:45:00",
      updatedAt: "2026-05-02T08:00:00",
      slaDeadline: "2026-05-02T19:45:00",
      slaTarget: 8 * 60,
      tags: ["#qc", "#poka-yoke"],
      worklog: [{ user: "u3", min: 30, when: "2026-05-01T16:00", note: "MAC adresi doğrulama, değişen parça listesi alındı" }],
      attachments: [{ name: "tork-log.txt", size: "92 KB", kind: "log" }],
    },
    {
      id: "TK-2838", title: "Boyahane access point AP-12 internet keşfedemiyor",
      productId: "net", issue: "Access Point Donanım Arızası",
      priority: "medium", status: "new",
      reporter: "c2", assignee: null,
      createdAt: "2026-05-02T07:55:00",
      updatedAt: "2026-05-02T07:55:00",
      slaDeadline: "2026-05-02T19:55:00",
      slaTarget: 12 * 60,
      tags: ["#network"],
      worklog: [],
      attachments: [],
    },
    {
      id: "TK-2837", title: "Hat-3 Kanban kartı okuma hatası",
      productId: "kanban", issue: "Dijital Kanban Kartı Okuma Hatası",
      priority: "medium", status: "in_progress",
      reporter: "c1", assignee: "u4",
      createdAt: "2026-04-29T13:20:00",
      updatedAt: "2026-05-02T09:00:00",
      slaDeadline: "2026-05-02T13:20:00",
      slaTarget: 12 * 60,
      tags: ["#kanban"],
      worklog: [],
      attachments: [],
    },
    {
      id: "TK-2836", title: "Sensör S-44 ham veri göndermeyi durdurdu",
      productId: "qc", issue: "Sensör İletişim Hatası",
      priority: "high", status: "resolved",
      reporter: "c4", assignee: "u3",
      createdAt: "2026-04-28T10:10:00",
      updatedAt: "2026-05-01T17:30:00",
      slaDeadline: "2026-04-28T18:10:00",
      slaTarget: 8 * 60,
      tags: ["#qc"],
      worklog: [{ user: "u3", min: 90, when: "2026-04-29T11:00", note: "Kablo değişimi" }],
      attachments: [],
      resolutionNote: "Sensör veri kablosu hasarlıydı. Kablo değiştirildi, sinyal seviyesi normal.",
    },
    {
      id: "TK-2835", title: "El terminali ET-09 IP çakışması",
      productId: "net", issue: "El Terminali IP Çakışması",
      priority: "low", status: "closed",
      reporter: "c3", assignee: "u1",
      createdAt: "2026-04-25T09:15:00",
      updatedAt: "2026-04-26T16:00:00",
      slaDeadline: "2026-04-27T09:15:00",
      slaTarget: 24 * 60,
      tags: ["#network"],
      worklog: [{ user: "u1", min: 25, when: "2026-04-26T15:30", note: "DHCP rezervasyonu" }],
      attachments: [],
      resolutionNote: "Statik IP atandı, çakışma giderildi.",
    },
    {
      id: "TK-2834", title: "SQL replication 14:00'de 12 dakika gecikmeli",
      productId: "uts", issue: "SQL Senkronizasyon Hatası",
      priority: "high", status: "in_progress",
      reporter: "c1", assignee: "u5",
      createdAt: "2026-05-01T15:00:00",
      updatedAt: "2026-05-02T08:30:00",
      slaDeadline: "2026-05-01T23:00:00",
      slaTarget: 8 * 60,
      tags: ["#mes"],
      breached: true,
      worklog: [],
      attachments: [],
    },
    {
      id: "TK-2833", title: "Kalite veritabanı erişim hatası — kullanıcı sınırı?",
      productId: "qc", issue: "Kalite Veritabanı Erişim Sorunu",
      priority: "medium", status: "new",
      reporter: "c4", assignee: null,
      createdAt: "2026-05-02T09:30:00",
      updatedAt: "2026-05-02T09:30:00",
      slaDeadline: "2026-05-02T21:30:00",
      slaTarget: 12 * 60,
      tags: ["#qc", "#db"],
      worklog: [],
      attachments: [],
    },
    {
      id: "TK-2832", title: "Wi-Fi sinyali B koridorunda zayıf",
      productId: "kanban", issue: "Wi-Fi Sinyal Zayıflığı",
      priority: "low", status: "waiting_customer",
      reporter: "c3", assignee: "u1",
      createdAt: "2026-04-30T14:00:00",
      updatedAt: "2026-05-01T11:20:00",
      slaDeadline: "2026-05-01T14:00:00",
      slaTarget: 24 * 60,
      tags: ["#network", "#kanban"],
      worklog: [],
      attachments: [],
    },
    {
      id: "TK-2831", title: "Sunucu veri yazma gecikmesi - 200ms üzeri",
      productId: "uts", issue: "Sunucu Veri Yazma Gecikmesi",
      priority: "medium", status: "resolved",
      reporter: "c1", assignee: "u5",
      createdAt: "2026-04-27T08:00:00",
      updatedAt: "2026-04-30T15:00:00",
      slaDeadline: "2026-04-27T20:00:00",
      slaTarget: 12 * 60,
      tags: ["#mes"],
      worklog: [],
      attachments: [],
      resolutionNote: "İndeks yeniden oluşturuldu, IO optimize edildi.",
    },
    {
      id: "TK-2830", title: "Port aktivasyon talebi — yeni hat 5 paneli",
      productId: "net", issue: "Port Aktivasyon Talebi",
      priority: "low", status: "closed",
      reporter: "c2", assignee: "u1",
      createdAt: "2026-04-22T10:00:00",
      updatedAt: "2026-04-23T13:00:00",
      slaDeadline: "2026-04-24T10:00:00",
      slaTarget: 48 * 60,
      tags: ["#network"],
      worklog: [],
      attachments: [],
    },
  ];

  // Sample comments per ticket (only seeded for the highlighted detail ticket)
  const comments = {
    "TK-2841": [
      { id: 1, user: "c1", kind: "external", text: "Vardiya başında ekran 4 her 30 saniyede bir yaklaşık 8 saniye boyunca donuyor. Hat duruşuna sebep oluyor.", at: "2026-04-30T08:14:00" },
      { id: 2, user: "u2", kind: "external", text: "Merhaba, log dosyası için teşekkürler. SQL replication tarafında bir gecikme görünüyor, inceliyoruz.", at: "2026-04-30T10:30:00" },
      { id: 3, user: "u2", kind: "internal", text: "DB-02 üzerinde wait_event_type IPC. Hülya'ya ping atıyorum, replication slot dolu olabilir.", at: "2026-04-30T10:35:00" },
      { id: 4, user: "u5", kind: "internal", text: "Onayladım, slot 9.2GB. Vacuum + slot tetikledim. Şimdi izliyoruz.", at: "2026-05-01T14:30:00" },
      { id: 5, user: "u2", kind: "external", text: "Geçici bir iyileşme görüyoruz. Bu öğleden sonra yeni bir ölçüm alabilir misiniz?", at: "2026-05-02T09:15:00" },
    ],
  };

  const activity = {
    "TK-2841": [
      { at: "2026-04-30T08:14:00", who: "c1", text: "ticket'ı açtı" },
      { at: "2026-04-30T08:16:00", who: "system", text: "SLA hedefi: 8 saat (Yüksek öncelik)" },
      { at: "2026-04-30T09:02:00", who: "u2", text: "ticket'ı kendine atadı, durumu In Progress'e aldı" },
      { at: "2026-05-01T14:30:00", who: "u2", text: "45dk worklog ekledi" },
      { at: "2026-05-02T09:15:00", who: "u2", text: "yorum ekledi" },
    ],
  };

  return { products, agents, customers, manager, tickets, comments, activity };
})();
